CXX = c++ 
CXXFLAGS = -std=c++17

Maximum_Sub_Sum: MaximumSubsequenceSum.cc
	$(CXX) $(CXXFLAGS) $^ -o $@

Josephus: josephus.cc
	$(CXX) $(CXXFLAGS) $^ -o $@

Longest_Sequence: longest_sequence.cc
	$(CXX) $(CXXFLAGS) $^ -o $@

