CXX = c++ 
CXXFLAGS = -std=c++20
INCLUDE_FLAGS = -I ~/cpp_libs/

insertion_sort: insertion_sort.cc
	$(CXX) $(CXXFLAGS) $^ -o $@

shell_sort: shell_sort.cc
	$(CXX) $(CXXFLAGS) $^ -o $@

selection_sort: selection_sort.cc
	$(CXX) $(CXXFLAGS) $^ -o $@

quicksort: quicksort.cc
	$(CXX) $(CXXFLAGS) $^ -o $@